ci: add updated package information to CI

diff --git a/.github/workflows/trigger-9.yml b/.github/workflows/trigger-9.yml
--- a/.github/workflows/trigger-9.yml
+++ b/.github/workflows/trigger-9.yml
@@ -133,45 +133,66 @@ jobs:
               echo "osbuild_composer_version_96=$OSBUILD_COMPOSER_VERSION_96" >> $GITHUB_OUTPUT
               echo "composer_cli_version_96=$COMPOSER_CLI_VERSION_96" >> $GITHUB_OUTPUT
 
-              GRUB2_VERSION_96=$(curl -s "${COMPOSE_URL_96}/${COMPOSE_ID_96}/compose/BaseOS/x86_64/os/Packages/" | grep -ioE ">grub2-common-[0-9].*<" | tr -d "><")
-              echo "grub2_version_96=$GRUB2_VERSION_96" >> $GITHUB_OUTPUT
-
-              OSTREE_VERSION_96=$(curl -s "${COMPOSE_URL_96}/${COMPOSE_ID_96}/compose/AppStream/x86_64/os/Packages/" | grep -ioE ">ostree-[0-9].*x86_64.*<" | tr -d "><")
-              echo "ostree_version_96=$OSTREE_VERSION_96" >> $GITHUB_OUTPUT
-
-              RPM_OSTREE_VERSION_96=$(curl -s "${COMPOSE_URL_96}/${COMPOSE_ID_96}/compose/AppStream/x86_64/os/Packages/" | grep -ioE ">rpm-ostree-[0-9].*<" | tr -d "><")
-              echo "rpm_ostree_version_96=$RPM_OSTREE_VERSION_96" >> $GITHUB_OUTPUT
-
-              KERNEL_VERSION_96=$(curl -s "${COMPOSE_URL_96}/${COMPOSE_ID_96}/compose/BaseOS/x86_64/os/Packages/" | grep -ioE ">kernel-modules-[0-9].*<" | tr -d "><")
-              echo "kernel_version_96=$KERNEL_VERSION_96" >> $GITHUB_OUTPUT
-
-
               curl -s ${COMPOSE_URL_96}/ --output COMPOSES
               COMPOSES=$(cat -n COMPOSES)
               line=$(echo "${COMPOSES}" | grep ${COMPOSE_ID_96} | cut -b 1-7)
               old_line=$((line - 1))
               OLD_COMPOSE_ID_96=$(echo "${COMPOSES}" | grep $old_line | tr -d "><" | grep -oP 'RHEL-.+?-updates-\d+\.\d+' | tail -1)
 
-              OLD_OSBUILD_VERSION_96=$(curl -s "${COMPOSE_URL_96}/${OLD_COMPOSE_ID_96}/compose/AppStream/x86_64/os/Packages/" | grep -ioE ">osbuild-[0-9].*<" | tr -d "><")
-              OLD_OSBUILD_COMPOSER_VERSION_96=$(curl -s "${COMPOSE_URL_96}/${OLD_COMPOSE_ID_96}/compose/AppStream/x86_64/os/Packages/" | grep -ioE ">osbuild-composer-[0-9].*<" | tr -d "><")
-              OLD_COMPOSER_CLI_VERSION_96=$(curl -s "${COMPOSE_URL_96}/${OLD_COMPOSE_ID_96}/compose/AppStream/x86_64/os/Packages/" | grep -ioE ">weldr-client-[0-9].*<" | tr -d "><")
-              echo "old_osbuild_version_96=$OLD_OSBUILD_VERSION_96" >> $GITHUB_OUTPUT
-              echo "old_osbuild_composer_version_96=$OLD_OSBUILD_COMPOSER_VERSION_96" >> $GITHUB_OUTPUT
-              echo "old_composer_cli_version_96=$OLD_COMPOSER_CLI_VERSION_96" >> $GITHUB_OUTPUT
-
-              OLD_GRUB2_VERSION_96=$(curl -s "${COMPOSE_URL_96}/${OLD_COMPOSE_ID_96}/compose/BaseOS/x86_64/os/Packages/" | grep -ioE ">grub2-common-[0-9].*<" | tr -d "><")
-              echo "old_grub2_version_96=$OLD_GRUB2_VERSION_96" >> $GITHUB_OUTPUT
-
-              OLD_OSTREE_VERSION_96=$(curl -s "${COMPOSE_URL_96}/${OLD_COMPOSE_ID_96}/compose/AppStream/x86_64/os/Packages/" | grep -ioE ">ostree-[0-9].*x86_64.*<" | tr -d "><")
-              echo "old_ostree_version_96=$OLD_OSTREE_VERSION_96" >> $GITHUB_OUTPUT
-
-              OLD_RPM_OSTREE_VERSION_96=$(curl -s "${COMPOSE_URL_96}/${OLD_COMPOSE_ID_96}/compose/AppStream/x86_64/os/Packages/" | grep -ioE ">rpm-ostree-[0-9].*<" | tr -d "><")
-              echo "old_rpm_ostree_version_96=$OLD_RPM_OSTREE_VERSION_96" >> $GITHUB_OUTPUT
-
-              OLD_KERNEL_VERSION_96=$(curl -s "${COMPOSE_URL_96}/${OLD_COMPOSE_ID_96}/compose/BaseOS/x86_64/os/Packages/" | grep -ioE ">kernel-modules-[0-9].*<" | tr -d "><")
-              echo "old_kernel_version_96=$OLD_KERNEL_VERSION_96" >> $GITHUB_OUTPUT
+              packages=("osbuild" "osbuild-composer" "weldr-client" "aardvark-dns" "acl" "alternatives" "audit-libs" "bootc" "bootupd" "bubblewrap" "bzip2-libs" "composefs" "conmon" "container-selinux" "containers-common" "coreutils" "cpio" "cracklib" "criu" "crun" "crypto-policies" "cryptsetup-libs" "cyrus-sasl-lib" "dbus" "device-mapper" "diffutils" "dracut" "expat" "file" "filesystem" "findutils" "fuse" "fuse3" "gawk" "gdbm-libs" "gettext" "glib2" "glibc" "gmp" "gnupg2" "gnutls" "gpgme" "grub2-common" "gzip" "iptables-libs" "jansson" "json-c" "json-glib" "kernel-modules" "keyutils-libs" "kmod" "kpartx" "krb5-libs" "libacl" "libarchive" "libassuan" "libattr" "libblkid" "libbrotli" "libcap" "libcom_err" "libcurl" "libdb" "libeconf" "libevent" "libfdisk" "libffi" "libgcc" "libgcrypt" "libgomp" "libgpg-error" "libidn2" "libkcapi" "libksba" "libmnl" "libmodulemd" "libmount" "libnet" "libnetfilter_conntrack" "libnfnetlink" "libnftnl" "libnghttp2" "libnl3" "libpsl" "libpwquality" "librepo" "librhsm" "libseccomp" "libselinux" "libsemanage" "libsepol" "libsigsegv" "libslirp" "libsmartcols" "libsolv" "libssh" "libtasn1" "libtool-ltdl" "libunistring" "libutempter" "libuuid" "libverto" "libxcrypt" "libxcrypt-compat" "libxml2" "libyaml" "libzstd" "lua-libs" "lz4-libs" "mpfr" "ncurses-libs" "netavark" "nettle" "nftables" "npth" "openldap" "openssl" "os-prober" "ostree" "p11-kit" "pam" "passt" "pcre" "pcre2" "pigz" "podman" "policycoreutils" "polkit-libs" "popt" "procps-ng" "protobuf-c" "python3" "readline" "redhat-release" "redhat-release-eula" "rpm" "rpm-libs" "rpm-ostree" "rpm-plugin-selinux" "selinux-policy" "shadow-utils" "skopeo" "slirp4netns" "sqlite-libs" "systemd" "systemd-libs" "systemd-pam" "systemd-udev" "tpm2-tss" "util-linux" "which" "xz" "xz-libs" "yajl" "zlib")
+              APPS_URL="${COMPOSE_URL_96}/${COMPOSE_ID_96}/compose/AppStream/x86_64/os/Packages/"
+              OLD_APPS_URL="${COMPOSE_URL_96}/${OLD_COMPOSE_ID_96}/compose/AppStream/x86_64/os/Packages/"
+              BASEOS_URL="${COMPOSE_URL_96}/${COMPOSE_ID_96}/compose/BaseOS/x86_64/os/Packages/"
+              OLD_BASEOS_URL="${COMPOSE_URL_96}/${OLD_COMPOSE_ID_96}/compose/BaseOS/x86_64/os/Packages/"
+              special_pkgs=("selinux-policy" "grub2-common" "osbuild" "container-selinux" "crypto-policies" "basesystem" "ca-certificates" "libssh-config" "passt-selinux" "publicsuffix-list-dafsa" "setup" "systemd-rpm-macros" "tzdata")
+              updated_pkgs=""
+              for pkg in "${packages[@]}"; do
+                  if [[ " ${special_pkgs[*]} " == *" ${pkg} "* ]]; then
+                      if curl -s "${APPS_URL}" | grep -ioE ">${pkg}-[0-9].*<"; then
+                          new=$(curl -s "${APPS_URL}" | grep -ioE ">${pkg}-[0-9].*<" | tr -d "><")
+                          old=$(curl -s "${OLD_APPS_URL}" | grep -ioE ">${pkg}-[0-9].*<" | tr -d "><")
+                          if [[ "$new" == "$old" ]]; then
+                              echo "Package ${pkg} not updated"
+                          else
+                              updated_pkgs+=$'\n'"${new}"
+                          fi
+                      elif curl -s "${BASEOS_URL}" | grep -ioE ">${pkg}-[0-9].*<"; then
+                          new=$(curl -s "${BASEOS_URL}" | grep -ioE ">${pkg}-[0-9].*<" | tr -d "><")
+                          old=$(curl -s "${OLD_APPS_URL}" | grep -ioE ">${pkg}-[0-9].*<" | tr -d "><")
+                          if [[ "$new" == "$old" ]]; then
+                              echo "Package ${pkg} not updated"
+                          else
+                              updated_pkgs+=$'\n'"${new}"
+                          fi
+                      else
+                          echo "NOT FOUND: $pkg" >&2
+                      fi
+                  else
+                      if curl -s "${APPS_URL}" | grep -ioE ">${pkg}-[0-9].*x86_64.*<"; then
+                          new=$(curl -s "${APPS_URL}" | grep -ioE ">${pkg}-[0-9].*x86_64.*<" | tr -d "><")
+                          old=$(curl -s "${OLD_APPS_URL}" | grep -ioE ">${pkg}-[0-9].*x86_64.*<" | tr -d "><")
+                          if [[ "$new" == "$old" ]]; then
+                              echo "Package ${pkg} not updated"
+                          else
+                              updated_pkgs+=$'\n'"${new}"
+                          fi
+                      elif curl -s "${BASEOS_URL}" | grep -ioE ">${pkg}-[0-9].*x86_64.*<"; then
+                          new=$(curl -s "${BASEOS_URL}" | grep -ioE ">${pkg}-[0-9].*x86_64.*<" | tr -d "><")
+                          old=$(curl -s "${OLD_APPS_URL}" | grep -ioE ">${pkg}-[0-9].*x86_64.*<" | tr -d "><")
+                          if [[ "$new" == "$old" ]]; then
+                              echo "Package ${pkg} not updated"
+                          else
+                              updated_pkgs+=$'\n'"${new}"
+                          fi
+                      else
+                          echo "NOT FOUND: $pkg" >&2
+                      fi
+                  fi
+              done
+              echo "updated_pkgs<<EOF" >> $GITHUB_OUTPUT
+              echo "${updated_pkgs}" >> $GITHUB_OUTPUT
+              echo "EOF" >> $GITHUB_OUTPUT
           fi
-
           echo "rhel96_compose=$COMPOSE_ID_96" >> $GITHUB_OUTPUT
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -191,18 +212,8 @@ jobs:
       osbuild_version_96: ${{ steps.check_compose_id_96.outputs.osbuild_version_96 }}
       osbuild_composer_version_96: ${{ steps.check_compose_id_96.outputs.osbuild_composer_version_96 }}
       composer_cli_version_96: ${{ steps.check_compose_id_96.outputs.composer_cli_version_96 }}
-      grub2_version_96: ${{ steps.check_compose_id_96.outputs.grub2_version_96 }}
-      ostree_version_96: ${{ steps.check_compose_id_96.outputs.ostree_version_96 }}
-      rpm_ostree_version_96: ${{ steps.check_compose_id_96.outputs.rpm_ostree_version_96 }}
-      kernel_version_96: ${{ steps.check_compose_id_96.outputs.kernel_version_96 }}
-      old_osbuild_version_96: ${{ steps.check_compose_id_96.outputs.old_osbuild_version_96 }}
-      old_osbuild_composer_version_96: ${{ steps.check_compose_id_96.outputs.old_osbuild_composer_version_96 }}
-      old_composer_cli_version_96: ${{ steps.check_compose_id_96.outputs.old_composer_cli_version_96 }}
-      old_grub2_version_96: ${{ steps.check_compose_id_96.outputs.old_grub2_version_96 }}
-      old_ostree_version_96: ${{ steps.check_compose_id_96.outputs.old_ostree_version_96 }}
-      old_rpm_ostree_version_96: ${{ steps.check_compose_id_96.outputs.old_rpm_ostree_version_96 }}
-      old_kernel_version_96: ${{ steps.check_compose_id_96.outputs.old_kernel_version_96 }}
       pr_running_96: ${{ steps.check_compose_id_96.outputs.pr_running_96 }}
+      updated_pkgs: ${{ steps.check_compose_id_96.outputs.updated_pkgs }}
 
   rhel-9-4:
     needs: check-compose
@@ -341,22 +352,13 @@ jobs:
           body: |
             RHEL 9.6 compose ${{ needs.check-compose.outputs.rhel96_compose }}
             - Date: ${{ steps.date.outputs.date }}
-            - Packages:
+            - Osbuild version:
                 - ${{ needs.check-compose.outputs.osbuild_version_96 }}
                 - ${{ needs.check-compose.outputs.osbuild_composer_version_96 }}
                 - ${{ needs.check-compose.outputs.composer_cli_version_96 }}
-                - ${{ needs.check-compose.outputs.grub2_version_96 }}
-                - ${{ needs.check-compose.outputs.ostree_version_96 }}
-                - ${{ needs.check-compose.outputs.rpm_ostree_version_96 }}
-                - ${{ needs.check-compose.outputs.kernel_version_96 }}
-            - Packages(in previous compose):
-                - ${{ needs.check-compose.outputs.old_osbuild_version_96 }}
-                - ${{ needs.check-compose.outputs.old_osbuild_composer_version_96 }}
-                - ${{ needs.check-compose.outputs.old_composer_cli_version_96 }}
-                - ${{ needs.check-compose.outputs.old_grub2_version_96 }}
-                - ${{ needs.check-compose.outputs.old_ostree_version_96 }}
-                - ${{ needs.check-compose.outputs.old_rpm_ostree_version_96 }}
-                - ${{ needs.check-compose.outputs.old_kernel_version_96 }}
+            - Updated packages:
+                - ${{ needs.check-compose.outputs.updated_pkgs }}
+
 
       - name: Enable Pull Request Automerge
         if: steps.cpr.outputs.pull-request-operation == 'created'
